In [ ]:
import torch

In [ ]:
#VECTOR
VECTOR = torch.tensor([1, 4])

In [ ]:
VECTOR.ndim

1

In [ ]:
VECTOR.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[2, 7], [3, 5]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 3, 5],
                        [8, 3, 4],
                        [5, 6, 2]
                        ]])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 3, 5],
        [8, 3, 4],
        [5, 6, 2]])

### Random tensors

In [ ]:
# Create a random tensor of size of (3, 4)
random_tensor = torch.rand(3, 4)

In [ ]:
random_tensor

tensor([[0.6327, 0.8861, 0.9626, 0.9990],
        [0.9920, 0.2243, 0.8767, 0.6827],
        [0.4771, 0.9765, 0.3211, 0.4497]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel [R, G, B]

In [ ]:
random_image_size_tensor

tensor([[[0.3089, 0.0264, 0.5740],
         [0.4170, 0.8036, 0.8766],
         [0.0195, 0.0073, 0.1793],
         ...,
         [0.0301, 0.4065, 0.2831],
         [0.5463, 0.9411, 0.3481],
         [0.6540, 0.4289, 0.9405]],

        [[0.9134, 0.2674, 0.3782],
         [0.4565, 0.8464, 0.9939],
         [0.0108, 0.0169, 0.7928],
         ...,
         [0.9198, 0.6656, 0.2665],
         [0.9980, 0.3046, 0.9514],
         [0.2220, 0.2391, 0.2921]],

        [[0.6776, 0.4480, 0.4605],
         [0.5862, 0.4805, 0.9072],
         [0.7962, 0.9084, 0.1427],
         ...,
         [0.3565, 0.5243, 0.2526],
         [0.2176, 0.8988, 0.7333],
         [0.8766, 0.0025, 0.1602]],

        ...,

        [[0.1963, 0.7758, 0.9785],
         [0.7815, 0.1501, 0.2833],
         [0.9372, 0.9622, 0.1331],
         ...,
         [0.8625, 0.2248, 0.3108],
         [0.4912, 0.1772, 0.9601],
         [0.6099, 0.1334, 0.8524]],

        [[0.2477, 0.5617, 0.2983],
         [0.5959, 0.3039, 0.1546],
         [0.

In [ ]:
### Zeros and ones tensors

In [ ]:
## tensor with all zeros
zeros = torch.zeros(size=(3, 4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
## tensor with all ones
ones = torch.ones(size=(1, 3, 4))

In [ ]:
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### Creating a range of tensors and tensors-like

In [ ]:
#Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the big errors you'll face into PyTorch and DL:
1. Tensors not right Datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # datatype of the tensor (e.g : float32, float16)
                               device=None, # What device ur tensor on
                               requires_grad=False # whether or not track gradients with this tensor operation
                               )

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors
### Tensor datatypes

1. Tensors not right Datatype : get info using `tensor.dtype`
2. Tensors not right shape : get info using `tensor.shape`
3. Tensors not on the right device : get info using ``tensor.device``

In [ ]:
#Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9384, 0.1322, 0.0095, 0.6128],
        [0.9633, 0.4741, 0.9466, 0.9398],
        [0.5770, 0.9824, 0.9544, 0.5306]])

In [ ]:
#Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"device tensor is on: {some_tensor.device}")

tensor([[0.9384, 0.1322, 0.0095, 0.6128],
        [0.9633, 0.4741, 0.9466, 0.9398],
        [0.5770, 0.9824, 0.9544, 0.5306]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication
* Devision
* Matrix multiplication


In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
# example multiplying by 10
tensor * 10
# we can use torch build-in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two mains ways of performing multiplication in neural networks and DL

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix mutliplication needs to satisfy:

1. The inner dimensions must match:
* ``(3, 2) @ (3, 2)`` won't work
* ``(2, 3) @ (3, 2)`` will work
* ``(3, 2) @ (2, 3)`` will work

2. The resulting matrix has the shape of the outer dimensions:

* ``(2, 3) @ (3, 2) -> (2, 2)``
* ``(3, 2) @ (2, 3) -> (3, 3)``

In [ ]:
# Element wise
print(tensor, ' * ', tensor)
print(tensor * tensor)

tensor([1, 2, 3])  *  tensor([1, 2, 3])
tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 476 µs, sys: 750 µs, total: 1.23 ms
Wall time: 1.16 ms


tensor(14)

In [ ]:
# matrix multiplication by hand
%%time
sum = 0
for i in range(len(tensor)):
  sum+=tensor[i] * tensor[i]

print(sum)

tensor(14)
CPU times: user 2.61 ms, sys: 0 ns, total: 2.61 ms
Wall time: 2.47 ms


In [ ]:
 # Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fixe our tensor shape issues we can manipulate the shape of one of our tensors using a **transpose**

A **Transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T.shape, tensor_B.shape ## after transposing we see that now the rule is satisfied and we can mm the two tensors

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)

In [ ]:
# Find the min
x.min()

tensor(0)

In [ ]:
# Find the max
x.max()

tensor(90)

In [ ]:
# find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
# find the sum
x.sum()

tensor(450)

### Finding the positional min and max

In [ ]:
# Finding the position in tensor with the min or max value
print(x)
print(f"Position of the min is in the index : {x.argmin()}")
print(f"Position of the max is in the index : {x.argmax()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Position of the min is in the index : 0
Position of the max is in the index : 9


In [ ]:
x[x.argmax()]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each others (vstack) or side by side (hstack)
*  Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extre dimension
x_reshaped = x.reshape(-1, 3, 3)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]),
 3)

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Stack tensors on top of each others

In [ ]:
x_stacked = torch.stack([x, x, x],dim=1)

In [ ]:
x_stacked

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 3, 3])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
torch.squeeze(x_reshaped).shape

torch.Size([3, 3])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])
Previous shape: torch.Size([1, 3, 3])

New tensor: tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
New shape: torch.Size([3, 3])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Previous shape: torch.Size([3, 3])

New tensor: tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])
New shape: torch.Size([1, 3, 3])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, heigh

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (Selecting data from tensors)

In [1]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# Let's index on our new tensor
x[0][2][2]

tensor(9)

In [3]:
# You can use ":" to select "all" of a target dimension
x[0][2][:]

tensor([7, 8, 9])

In [6]:
x[:, :, 1]

tensor([[2, 5, 8]])

### PyTorch tensors & NumPy
NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> ``torch.from_numpy(ndarray)``
* PyTorch tensor -> ``NumPy -> torch.Tensor.numpy()``

In [10]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [11]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducbility (trying to take random out of random)
In short how a neural network learns:

``start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...``

To reduce the randomness in neural networks and PyTorch comes the concept of a ``random seed``.

Essentially what the random seed does is "flavour" the randomness.

In [12]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7755, 0.1527, 0.0886, 0.4714],
        [0.9509, 0.1985, 0.5415, 0.7113],
        [0.1423, 0.9719, 0.2889, 0.6162]])
tensor([[0.6227, 0.7030, 0.4137, 0.2758],
        [0.4215, 0.0256, 0.0541, 0.3721],
        [0.0265, 0.9820, 0.3580, 0.4274]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [13]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

1. Getting a GPU
Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get: https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [15]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [16]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [17]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [19]:
torch.cuda.device_count()

0

In [20]:
## after using GPU as runtime

In [1]:
!nvidia-smi

Fri Jan 26 10:40:33 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [5]:

# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 4. Moving tensors back to the CPU

In [7]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [9]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')