In [2]:
import torch

In [3]:
#VECTOR
VECTOR = torch.tensor([1, 4])

In [4]:
VECTOR.ndim

1

In [ ]:
VECTOR.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[2, 7], [3, 5]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 3, 5],
                        [8, 3, 4],
                        [5, 6, 2]
                        ]])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 3, 5],
        [8, 3, 4],
        [5, 6, 2]])

### Random tensors

In [ ]:
# Create a random tensor of size of (3, 4)
random_tensor = torch.rand(3, 4)

In [ ]:
random_tensor

tensor([[0.6327, 0.8861, 0.9626, 0.9990],
        [0.9920, 0.2243, 0.8767, 0.6827],
        [0.4771, 0.9765, 0.3211, 0.4497]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel [R, G, B]

In [ ]:
random_image_size_tensor

tensor([[[0.3089, 0.0264, 0.5740],
         [0.4170, 0.8036, 0.8766],
         [0.0195, 0.0073, 0.1793],
         ...,
         [0.0301, 0.4065, 0.2831],
         [0.5463, 0.9411, 0.3481],
         [0.6540, 0.4289, 0.9405]],

        [[0.9134, 0.2674, 0.3782],
         [0.4565, 0.8464, 0.9939],
         [0.0108, 0.0169, 0.7928],
         ...,
         [0.9198, 0.6656, 0.2665],
         [0.9980, 0.3046, 0.9514],
         [0.2220, 0.2391, 0.2921]],

        [[0.6776, 0.4480, 0.4605],
         [0.5862, 0.4805, 0.9072],
         [0.7962, 0.9084, 0.1427],
         ...,
         [0.3565, 0.5243, 0.2526],
         [0.2176, 0.8988, 0.7333],
         [0.8766, 0.0025, 0.1602]],

        ...,

        [[0.1963, 0.7758, 0.9785],
         [0.7815, 0.1501, 0.2833],
         [0.9372, 0.9622, 0.1331],
         ...,
         [0.8625, 0.2248, 0.3108],
         [0.4912, 0.1772, 0.9601],
         [0.6099, 0.1334, 0.8524]],

        [[0.2477, 0.5617, 0.2983],
         [0.5959, 0.3039, 0.1546],
         [0.

In [ ]:
### Zeros and ones tensors

In [ ]:
## tensor with all zeros
zeros = torch.zeros(size=(3, 4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
## tensor with all ones
ones = torch.ones(size=(1, 3, 4))

In [ ]:
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### Creating a range of tensors and tensors-like

In [ ]:
#Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the big errors you'll face into PyTorch and DL:
1. Tensors not right Datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # datatype of the tensor (e.g : float32, float16)
                               device=None, # What device ur tensor on
                               requires_grad=False # whether or not track gradients with this tensor operation
                               )

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors
### Tensor datatypes

1. Tensors not right Datatype : get info using `tensor.dtype`
2. Tensors not right shape : get info using `tensor.shape`
3. Tensors not on the right device : get info using ``tensor.device``

In [ ]:
#Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9384, 0.1322, 0.0095, 0.6128],
        [0.9633, 0.4741, 0.9466, 0.9398],
        [0.5770, 0.9824, 0.9544, 0.5306]])

In [ ]:
#Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"device tensor is on: {some_tensor.device}")

tensor([[0.9384, 0.1322, 0.0095, 0.6128],
        [0.9633, 0.4741, 0.9466, 0.9398],
        [0.5770, 0.9824, 0.9544, 0.5306]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication
* Devision
* Matrix multiplication


In [6]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
# example multiplying by 10
tensor * 10
# we can use torch build-in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two mains ways of performing multiplication in neural networks and DL

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix mutliplication needs to satisfy:

1. The inner dimensions must match:
* ``(3, 2) @ (3, 2)`` won't work
* ``(2, 3) @ (3, 2)`` will work
* ``(3, 2) @ (2, 3)`` will work

2. The resulting matrix has the shape of the outer dimensions:

* ``(2, 3) @ (3, 2) -> (2, 2)``
* ``(3, 2) @ (2, 3) -> (3, 3)``

In [10]:
# Element wise
print(tensor, ' * ', tensor)
print(tensor * tensor)

tensor([1, 2, 3])  *  tensor([1, 2, 3])
tensor([1, 4, 9])


In [26]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 476 µs, sys: 750 µs, total: 1.23 ms
Wall time: 1.16 ms


tensor(14)

In [25]:
# matrix multiplication by hand
%%time
sum = 0
for i in range(len(tensor)):
  sum+=tensor[i] * tensor[i]

print(sum)

tensor(14)
CPU times: user 2.61 ms, sys: 0 ns, total: 2.61 ms
Wall time: 2.47 ms


In [27]:
 # Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [28]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fixe our tensor shape issues we can manipulate the shape of one of our tensors using a **transpose**

A **Transpose** switches the axes or dimensions of a given tensor

In [31]:
tensor_B.T.shape, tensor_B.shape ## after transposing we see that now the rule is satisfied and we can mm the two tensors

(torch.Size([2, 3]), torch.Size([3, 2]))

In [34]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### finding the min, max, mean, sum, etc (tensor aggregation)

In [49]:
# Create a tensor
x = torch.arange(0, 100, 10)

In [50]:
# Find the min
x.min()

tensor(0)

In [51]:
# Find the max
x.max()

tensor(90)

In [53]:
# find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [54]:
# find the sum
x.sum()

tensor(450)